age=input("Enter your age")
name=input("Enter your name")
per=input("Entre per%")
print("Welcome to python programming")
print("My Age=:",age)
print(type(age))
print("My Name=:",name)
print(type(name))
print("My Per=:",per)
print(type(per))
